// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"Task_LiXiaYu","status":true,"description":"","parameters":{}},
{"name":"Tasks_Task_LiXiaYu","status":true,"description":"","parameters":{}},
{"name":"Manager_Task_LiXiaYu","status":true,"description":"","parameters":{}},
{"name":"ShowTextWithPicture","status":false,"description":"","parameters":{}},
{"name":"JH_msgpush","status":false,"description":"一个消息推送小脚本","parameters":{}}
];
